---
# tasks file for release-installer
- name: Check if binary already installed
  stat:
    path: "{{ install_path }}/{{ archive_binary_filename | basename }}"
  register: file_status
- block:
  - name: Create tempory directory
    tempfile:
      state: directory
    register: tempdirectory

  - name: Download archive
    get_url:
      force: true
      # yamllint disable-line rule:line-length
      url: "{{ archive_url }}"
      dest: "/tmp"
    register: downloaded_file

  - name: Extract {{ downloaded_file.dest }}
    unarchive:
      src: "{{ downloaded_file.dest }}"
      dest: "/tmp"
      remote_src: true
    register: archive

  - name: Install binary {{ install_path }}/{{ archive_binary_filename | basename }}
    become: true
    copy:
      mode: 755
      src: "{{ archive.dest }}/{{ archive_binary_filename }}"
      dest: "{{ install_path }}/"
      remote_src: true

  - name: Remove extracted archive
    ansible.builtin.file:
      path: "{{ tempdirectory }}"
      state: absent
  when: not file_status.stat.exists
